
CREATE TABLE VendorInformationRequest (
    supplier_vir_number VARCHAR(100),
    supplier_id INT,
    supplier_name VARCHAR(255),
    supplier_address TEXT,
    part_id INT,
    part_name VARCHAR(255),
    material_control_level VARCHAR(100),
    material_description TEXT,
    material_location VARCHAR(100),
    status_of_part VARCHAR(50),
    cause TEXT,
    corrective_action_taken TEXT,
    technical_justification TEXT,
    date_posted DATE,
    date_resolved DATE,
    reported_by VARCHAR(255),
    signatures VARCHAR(255)
);


INSERT INTO VendorInformationRequest VALUES ('VIR-9598', 1, 'Nelson and Sons', '4508 Cruz Lake Apt. 108, East Lawrencefurt, MT 11572', 6252, 'Learn Part', 'Medium', 'Both eight purpose soldier since yard.', 'East Charlesshire', 'Approved', 'Leg on those same apply.', 'Fine successful yourself hot once challenge begin million myself form.', 'Key series themselves light writer nothing career surface.', 2025-03-04, 2025-03-05, 'Brent Khan', 'Sean Mitchell');
INSERT INTO VendorInformationRequest VALUES ('VIR-4806', 2, 'Cooke, Walsh and Golden', '7321 Boyd Springs Apt. 688, Millerburgh, TN 80455', 8902, 'Crime Part', 'Low', 'Study leader reach within stuff.', 'New Bettyshire', 'Rejected', 'Still serious drop foot truth late against.', 'Small situation assume health magazine.', 'Ago heavy between feeling feeling word interest stuff approach pressure sister.', 2025-05-18, 2025-06-15, 'Alisha Sawyer', 'Kelli Allison');
INSERT INTO VendorInformationRequest VALUES ('VIR-3168', 3, 'Frost-Richards', '14947 Christopher Vista, New Josestad, KS 22768', 9479, 'Final Part', 'Medium', 'Speech up sign tend tell they data recently.', 'Port Isabella', 'Approved', 'Main body TV establish itself fish seat.', 'Foreign both back third really event traditional product stuff concern town.', 'Game bank upon act family shake.', 2024-11-18, 2024-12-09, 'Marcus King', 'Richard Robles');
INSERT INTO VendorInformationRequest VALUES ('VIR-1502', 4, 'Rogers-Anderson', '728 Steven Rue Apt. 720, Parkerside, MN 23514', 5450, 'Interview Part', 'High', 'Kind window rest item.', 'Davischester', 'Rejected', 'Inside beat imagine education.', 'Himself phone myself type feeling.', 'Away set thousand add wide peace listen with property middle.', 2025-04-22, 2025-05-19, 'Amber Mccormick', 'Shannon Hernandez');
INSERT INTO VendorInformationRequest VALUES ('VIR-7873', 5, 'Keller, Lloyd and Gonzalez', 'Unit 5270 Box 5259, DPO AP 75519', 7605, 'Any Part', 'Low', 'Ability back cultural my almost practice discuss.', 'New Michael', 'Rejected', 'Benefit those situation task suggest cause often throw.', 'Glass weight different certain offer speak rock affect.', 'Charge vote total employee same add professor company box at poor citizen.', 2024-06-27, 2024-07-01, 'Travis Bates', 'Stephen Martinez');
INSERT INTO VendorInformationRequest VALUES ('VIR-2567', 6, 'Mayo-Johnson', '9822 Boyd Inlet, Ochoaside, AZ 27183', 8427, 'It Part', 'Low', 'Easy wind pull. Up life information democratic.', 'Johnsonfort', 'Rejected', 'Student trade management sense somebody though.', 'Every behind hear possible capital skin any real money.', 'Star southern single hair meeting attack policy north.', 2024-07-20, 2024-08-16, 'Emily Edwards', 'Matthew Walters');
INSERT INTO VendorInformationRequest VALUES ('VIR-9255', 7, 'Anderson Inc', '55469 Tyler Rapid, West David, IL 71820', 7747, 'Official Part', 'Low', 'Bad store level tonight.', 'Davidshire', 'Under Review', 'Nation fill upon strategy occur.', 'Congress heavy data black lot them table society.', 'Without movement movie form people practice western less fact know same fear.', 2024-07-07, 2024-08-03, 'Linda Alexander', 'Donald Cox');
INSERT INTO VendorInformationRequest VALUES ('VIR-2515', 8, 'Walker-Mclean', '0956 Chelsea Ways Apt. 721, East Michael, AR 47602', 3440, 'Above Part', 'Low', 'Hear white where attorney happen.', 'South Kellyside', 'Approved', 'Market always catch reveal.', 'Poor fish other simply huge color us skill.', 'Know need together score central court war.', 2025-02-09, 2025-03-04, 'Beth Santiago', 'Sarah Mcdonald');
INSERT INTO VendorInformationRequest VALUES ('VIR-1058', 9, 'Stephens Ltd', '618 Deborah Spur Apt. 250, South John, HI 49961', 3886, 'Value Part', 'Medium', 'Social mission film green continue single action.', 'Cruzland', 'Rejected', 'Town answer success that.', 'Room add with professional catch performance likely.', 'Well around better song kitchen cup follow.', 2024-07-02, 2024-07-19, 'Gary Ortiz', 'Austin Mcdonald');
INSERT INTO VendorInformationRequest VALUES ('VIR-9474', 10, 'Ward-Malone', '6115 Deanna Groves, Lake Angelaport, IN 02124', 1949, 'That Part', 'Medium', 'Explain bad sort hope teacher plan.', 'Lake Teresaton', 'Under Review', 'Your decide free bag but far financial.', 'Hospital fight student design oil charge street spend.', 'Appear off might treat item all nation campaign movement pattern company guy less.', 2024-08-14, 2024-08-18, 'Kim Kelley', 'Amy Campbell');
INSERT INTO VendorInformationRequest VALUES ('VIR-2277', 11, 'Willis, Johnston and York', '41751 Calderon Cliff Apt. 058, Osbornmouth, AK 82585', 5108, 'Business Part', 'Low', 'Difficult room describe piece push land series.', 'Lake Davidland', 'Approved', 'Remain choice few way when.', 'Bag democratic parent reach example.', 'Audience spend same sense boy most here certainly wife reason create box.', 2025-03-01, 2025-03-02, 'Katherine Howard', 'Ryan Scott');
INSERT INTO VendorInformationRequest VALUES ('VIR-1494', 12, 'Ruiz, Burke and Griffith', '9901 Johnson Mission, Smithtown, TX 84332', 5356, 'Public Part', 'Medium', 'Article event health student ever good eat.', 'Blankenshipmouth', 'Rejected', 'Near opportunity lay month follow certainly business appear.', 'Society data difference happen professor.', 'Growth civil late miss company figure officer.', 2024-08-09, 2024-09-05, 'Brittany Rodriguez MD', 'Michelle Perez');
INSERT INTO VendorInformationRequest VALUES ('VIR-6334', 13, 'Wong and Sons', '9938 Thomas Village, Guzmanstad, AK 94745', 5693, 'Campaign Part', 'High', 'Improve each simple seem mind baby.', 'Mcdonaldfort', 'Approved', 'Then law firm plan process save possible.', 'Industry consumer serve something other country others.', 'Rich bill adult prepare them anyone produce door site record level democratic house.', 2024-12-24, 2025-01-04, 'Olivia Anderson', 'Valerie White');
INSERT INTO VendorInformationRequest VALUES ('VIR-2245', 14, 'Quinn PLC', '50281 Thomas Vista, Seanchester, WY 35229', 5052, 'Room Part', 'High', 'Wife budget lawyer opportunity speak.', 'Fullerberg', 'Under Review', 'Case station discover child exist article coach.', 'Specific tough long expect ask arrive realize western order.', 'Owner environment traditional others happy accept subject above society official international city forward degree.', 2024-09-07, 2024-09-26, 'Kimberly Franklin', 'Leah Neal');
INSERT INTO VendorInformationRequest VALUES ('VIR-2544', 15, 'Barker-Price', '419 Ronald Stream, North Katrina, ME 34906', 6928, 'Return Part', 'High', 'Important base send music writer military.', 'Travisport', 'Approved', 'Represent new now bad cost possible possible.', 'Pick gun that culture clear.', 'Star firm oil next much factor focus dream deal anything relationship sell involve.', 2025-01-19, 2025-02-15, 'Nicole Mendoza', 'Amanda Thornton');
INSERT INTO VendorInformationRequest VALUES ('VIR-8465', 16, 'Johnson, Murphy and Tanner', '45953 Sarah Mountain, Meghanbury, CO 41748', 9244, 'Prove Part', 'Medium', 'Reality body politics finally strategy contain.', 'Hurstbury', 'Rejected', 'Head drug relationship open couple party.', 'East few building which study get role.', 'Beyond large late blood all mission serve truth likely.', 2024-08-06, 2024-08-24, 'Linda Carrillo', 'Susan Castro');
INSERT INTO VendorInformationRequest VALUES ('VIR-2561', 17, 'Mcgee Inc', '6042 Cheryl Parks Suite 704, Brandistad, MN 59431', 3844, 'Lay Part', 'High', 'Campaign again watch probably toward another.', 'Yolandaburgh', 'Under Review', 'Side knowledge brother policy pattern mind drug college.', 'Camera main audience third system party later kitchen.', 'Statement blue rest me popular score international window trouble look agree.', 2025-03-27, 2025-03-30, 'Matthew Gilmore', 'Jordan Cunningham');
INSERT INTO VendorInformationRequest VALUES ('VIR-6626', 18, 'Erickson PLC', '23495 Wilkinson Garden Suite 477, New Lori, PA 23507', 8876, 'Option Part', 'Low', 'Reach serve type common.', 'New Paulton', 'Under Review', 'Against wear weight half allow treatment oil.', 'Significant start less argue third wide crime some weight.', 'Happy economy but treatment drop kitchen eight provide serve perform hard.', 2024-06-19, 2024-06-30, 'Tony Bailey', 'Jonathan Moore');
INSERT INTO VendorInformationRequest VALUES ('VIR-7665', 19, 'Woods Inc', '700 Crystal Islands, Fosterside, ME 64918', 7562, 'Half Part', 'High', 'Capital onto model order conference.', 'Gillchester', 'Approved', 'These hair meeting manage guy interview edge.', 'Figure glass big up.', 'Return artist direction scientist agreement stage me coach clearly seat by social across.', 2025-02-15, 2025-03-02, 'Kimberly Oneal', 'Lucas Gardner');
INSERT INTO VendorInformationRequest VALUES ('VIR-4364', 20, 'Smith, Smith and Booth', '75449 Woodard Squares Suite 651, Kimberlyshire, WA 15511', 9358, 'Economic Part', 'High', 'View husband Mr become.', 'Port Madisonton', 'Approved', 'Expert true operation big.', 'Do on study pay.', 'Myself book agree authority enter less pass contain Congress mean.', 2024-10-23, 2024-11-10, 'Lorraine Love', 'Brandon Kim DVM');
INSERT INTO VendorInformationRequest VALUES ('VIR-9087', 21, 'Fowler-Smith', '2163 Melanie Walk, Dennisside, WA 69149', 6291, 'Also Part', 'High', 'Professor inside chair open.', 'South Brandon', 'Under Review', 'While fast themselves out present choice.', 'Image mean just half candidate front across.', 'Save great bar along shake education sea seek truth customer best.', 2025-02-27, 2025-03-03, 'David Rodriguez', 'James Herrera');
INSERT INTO VendorInformationRequest VALUES ('VIR-7621', 22, 'Randolph LLC', '30002 Ashlee Cape, Jamesfurt, SC 57560', 3805, 'Grow Part', 'Low', 'Without job paper official seat threat.', 'Jayhaven', 'Approved', 'Interest report recent any.', 'Meet poor sister bag player road year such.', 'Four nothing cost mission win shoulder why network.', 2025-04-04, 2025-04-10, 'Dr. Christine Castro', 'Christopher Haynes');
INSERT INTO VendorInformationRequest VALUES ('VIR-9229', 23, 'Fox Inc', '9029 Mendez Port, Lake David, CT 84647', 7534, 'Ten Part', 'Medium', 'Where drive young leave standard.', 'Adamstown', 'Under Review', 'Key character get.', 'Certainly interesting goal structure western since.', 'Knowledge yeah travel indicate edge citizen physical base million issue.', 2024-08-29, 2024-09-05, 'Jason Walker', 'Denise Mayo');
INSERT INTO VendorInformationRequest VALUES ('VIR-5121', 24, 'Dennis, Miller and Miller', '40942 Michael Gardens Apt. 909, Port Kyleport, SD 73093', 9614, 'Everyone Part', 'Low', 'Watch international finish strategy firm.', 'North Selena', 'Approved', 'Onto indicate case goal possible follow quite.', 'Career nothing specific family fear movement suggest win shoulder.', 'Idea where lay certainly market customer economic.', 2024-07-08, 2024-08-01, 'Elizabeth Williams', 'Mr. John Gay DDS');
INSERT INTO VendorInformationRequest VALUES ('VIR-9375', 25, 'Byrd-Torres', '722 Tucker Ranch Apt. 350, South Lori, CA 32447', 6420, 'Report Part', 'High', 'Fall clearly picture after need.', 'Reedhaven', 'Approved', 'Need look people conference win.', 'Person so draw TV mouth building time room.', 'Poor stand those them maintain how despite responsibility as Republican we different boy.', 2025-04-01, 2025-04-21, 'Denise Blankenship', 'Vincent Harris');
INSERT INTO VendorInformationRequest VALUES ('VIR-8977', 26, 'Mullins, Miles and Ramsey', '8241 Lisa Via, Garciaport, OH 50148', 4222, 'Process Part', 'Low', 'Me air party door here change.', 'North Jenniferberg', 'Approved', 'Budget education nearly wish especially color.', 'Television decade figure free question gas.', 'Four under situation it resource different as sound to.', 2025-01-29, 2025-02-05, 'Holly Levy', 'Lauren Vang');
INSERT INTO VendorInformationRequest VALUES ('VIR-2951', 27, 'Larsen-Jones', '305 Howell Row Apt. 641, Youngfort, SD 23292', 8587, 'Service Part', 'High', 'Energy these because book attorney nearly be.', 'South Vincentland', 'Under Review', 'Provide onto south whose bar.', 'Indeed public together under commercial civil.', 'Reveal small stop star partner spring think whatever yard place firm even share.', 2024-12-31, 2025-01-12, 'Christina Casey', 'Anne Harmon');
INSERT INTO VendorInformationRequest VALUES ('VIR-9266', 28, 'Sanchez LLC', '6480 Amy Radial Apt. 695, North Kimberlytown, NM 20503', 2410, 'Customer Part', 'High', 'Institution phone else recent important smile.', 'Port Chelsea', 'Rejected', 'Few father pretty message watch forward beat total.', 'Natural according situation red kind expert.', 'Book matter level front democratic leave three bank expert apply foreign important tax.', 2025-05-09, 2025-05-19, 'Victoria Jordan', 'Jennifer Hancock');
INSERT INTO VendorInformationRequest VALUES ('VIR-3682', 29, 'Miles Ltd', '4973 Harris Groves, New Karen, AL 93214', 4437, 'Just Part', 'Medium', 'Financial guess admit plant go finish.', 'West Randyfurt', 'Rejected', 'Blood either commercial expert what go different.', 'Personal commercial network from speech line.', 'Fund change everything bad night throw understand stand response rather this little each.', 2025-02-24, 2025-03-18, 'Julie Hernandez', 'Mark Johnson');
INSERT INTO VendorInformationRequest VALUES ('VIR-5610', 30, 'Mcgee PLC', '608 Porter Radial Apt. 048, Maryshire, NM 60458', 4202, 'Again Part', 'Medium', 'Four the debate though test.', 'Port David', 'Under Review', 'Decide per fall real science cost population.', 'Simple whose oil put site family.', 'Yourself minute move to drop official occur president customer rest.', 2024-07-20, 2024-08-08, 'Thomas Guerrero', 'Robin Castro');
INSERT INTO VendorInformationRequest VALUES ('VIR-1679', 31, 'Morris-Gates', '712 Harrison Common Suite 343, East Thomasland, NJ 02028', 2106, 'Long Part', 'High', 'Support type lay.', 'Jessicahaven', 'Under Review', 'Central group however voice.', 'Movie put chance Democrat detail industry either senior just.', 'Many while under me country strategy south ready Congress hear everything.', 2024-10-31, 2024-11-29, 'John Zimmerman', 'Matthew Harris');
INSERT INTO VendorInformationRequest VALUES ('VIR-5643', 32, 'Marquez Group', '0039 Allen Path, Schroederstad, AL 22040', 9999, 'Join Part', 'High', 'Possible million address weight.', 'Mccoyland', 'Approved', 'Group at dark amount edge unit.', 'Laugh someone federal well feeling answer sport.', 'Go single two per space student month itself rule.', 2025-02-03, 2025-02-09, 'Gregory Rivera', 'Bernard Hill');
INSERT INTO VendorInformationRequest VALUES ('VIR-9638', 33, 'Harris Group', '898 Peggy Village, Port Thomas, ND 52745', 2733, 'Lead Part', 'High', 'Field worker part friend effect democratic chair.', 'South Sandrahaven', 'Under Review', 'Central partner down.', 'Bed approach thing exist force expert stage.', 'Manager he chance management foot concern owner magazine among growth past house.', 2025-02-04, 2025-02-09, 'Jennifer Lewis', 'Pamela Costa');
INSERT INTO VendorInformationRequest VALUES ('VIR-2993', 34, 'Vang, Byrd and Melendez', '86791 Vasquez Throughway, East James, NV 12304', 5747, 'Any Part', 'Low', 'Save example have media.', 'Port Hannah', 'Approved', 'Then knowledge son speech raise avoid.', 'Probably side sometimes alone material.', 'Join something hear far eat room exist attorney wait.', 2024-11-21, 2024-12-02, 'Danny Wyatt', 'Wendy Dunn');
INSERT INTO VendorInformationRequest VALUES ('VIR-1888', 35, 'Alvarez, Ray and Hester', '16001 Angela Row Suite 496, East Garymouth, WI 51786', 8357, 'Available Part', 'Medium', 'Question stock plan.', 'Hernandezchester', 'Rejected', 'Actually find school hundred just.', 'Another garden buy score officer medical hope our box.', 'Doctor decade like participant building activity face entire field resource.', 2024-08-06, 2024-08-27, 'Stephanie Morrison', 'Amy Gomez');
INSERT INTO VendorInformationRequest VALUES ('VIR-8221', 36, 'Morgan, Jones and Hill', '18027 Hanson Crescent, Christineshire, MO 90364', 3508, 'No Part', 'Medium', 'See seat responsibility yes population.', 'Port Edwardborough', 'Under Review', 'Walk prove along part.', 'See player wide step different stay.', 'Theory cell hope group ground trip free impact significant pass after.', 2025-05-02, 2025-05-19, 'Morgan Murillo', 'Maria Murray MD');
INSERT INTO VendorInformationRequest VALUES ('VIR-2118', 37, 'Branch LLC', '915 Daniel Freeway Suite 799, Amandamouth, LA 49067', 8478, 'Simply Part', 'Low', 'Such sure television several be career.', 'Kendrastad', 'Approved', 'Player include season image real necessary and.', 'Whatever decision memory heavy trial follow your responsibility heavy sister.', 'Stock everyone executive her single suddenly total.', 2024-08-04, 2024-08-05, 'Brian Hart', 'Cheryl Williams');
INSERT INTO VendorInformationRequest VALUES ('VIR-5285', 38, 'Kane Group', '48712 Mary Wall, West Margaretfort, MD 08795', 6667, 'Week Part', 'Medium', 'Something camera around style.', 'Brownview', 'Under Review', 'The guy nor clearly key society current.', 'Reason however authority decide drive fine.', 'Because phone meeting sure thank allow available political teach some enter.', 2024-12-29, 2025-01-22, 'Christopher Johnston', 'Erica Mcdonald');
INSERT INTO VendorInformationRequest VALUES ('VIR-9362', 39, 'Simmons-Huang', '87423 Brian Streets Suite 343, Port William, AR 29825', 5648, 'Part Part', 'High', 'Her life century friend late now fact.', 'West Alicialand', 'Approved', 'Can democratic we trip deep course.', 'Election million crime question together clearly.', 'Seven very capital measure left finish window choose position maintain clear.', 2024-12-23, 2025-01-01, 'Donald Thompson', 'Meghan Holt');
INSERT INTO VendorInformationRequest VALUES ('VIR-4159', 40, 'Powell LLC', 'PSC 7862, Box 0610, APO AA 63363', 9054, 'Several Part', 'Medium', 'Chance home run loss break daughter fish.', 'Lake Kathrynmouth', 'Approved', 'Light practice stage subject.', 'Forward someone place wish task course number bill movement.', 'Environmental ability into which heavy remember million against poor trip field can.', 2025-02-04, 2025-02-23, 'Donna Lee', 'Steven Hopkins');
INSERT INTO VendorInformationRequest VALUES ('VIR-9463', 41, 'Mcclure-Brown', '4536 Sullivan Meadows Suite 661, Bridgettown, NY 01492', 5768, 'Low Part', 'Medium', 'Then drug his. Own court our success.', 'South Jasonland', 'Rejected', 'Style it serious lead because owner edge.', 'Party see sing and camera check though prevent.', 'Board blue must nothing red laugh she certainly.', 2024-06-12, 2024-07-03, 'Steven Alexander', 'Sean Clark');
INSERT INTO VendorInformationRequest VALUES ('VIR-1248', 42, 'Lee, Lee and Hampton', '8495 Trevor Mall Suite 475, South John, GA 86317', 3013, 'Arrive Part', 'Medium', 'Face moment music enjoy other little weight.', 'Amandaside', 'Approved', 'Relationship stand me smile under analysis send.', 'State support our operation deep blood.', 'Response somebody seat themselves structure big exactly land none.', 2024-06-07, 2024-07-01, 'Brianna Harris', 'Bonnie Lewis');
INSERT INTO VendorInformationRequest VALUES ('VIR-6025', 43, 'Hill-Alexander', '2946 Jeremy Well Suite 302, Barbaraberg, VA 90177', 5336, 'Worker Part', 'Medium', 'Push who sound much study article.', 'Josephview', 'Rejected', 'If others marriage seven civil town.', 'Often system until gun purpose enjoy explain range.', 'Arrive bit along lay happy eight white.', 2025-03-05, 2025-03-15, 'Samuel Gibbs', 'Shawn Andrade');
INSERT INTO VendorInformationRequest VALUES ('VIR-8936', 44, 'Matthews, Lambert and Mclaughlin', '59461 Shawna Square Apt. 054, Poncechester, ND 55972', 3698, 'Toward Part', 'Medium', 'Teach stand director she phone teacher.', 'East Olivia', 'Rejected', 'Hot scientist than away.', 'Though notice themselves yes owner bar certainly respond.', 'Operation place finish budget strategy always.', 2024-12-24, 2025-01-15, 'Heidi Bryan', 'Tonya Hood');
INSERT INTO VendorInformationRequest VALUES ('VIR-6143', 45, 'Andrews-Cook', '4809 Thomas Harbors, Lake William, NY 15582', 6764, 'Hair Part', 'Medium', 'Together type two level wait land.', 'Angelaton', 'Approved', 'Section remain nothing book capital crime laugh.', 'Receive image must staff peace buy kind especially nothing.', 'Require remember current technology beyond check.', 2025-05-03, 2025-05-27, 'Abigail Fisher', 'Donna Ayers');
INSERT INTO VendorInformationRequest VALUES ('VIR-9601', 46, 'Gonzales Inc', '8942 Turner Mountains, Armstrongview, GA 08048', 4611, 'Increase Part', 'Low', 'True wife follow particularly bank over.', 'West Stephen', 'Under Review', 'Enjoy reason perform.', 'Make lose artist forward data.', 'Nor any market surface water along study check along region.', 2024-07-16, 2024-07-17, 'Joshua Martinez', 'Sarah Ho');
INSERT INTO VendorInformationRequest VALUES ('VIR-1388', 47, 'White-Reyes', '50426 William Radial Apt. 427, Garyland, MN 20958', 9059, 'Major Part', 'Medium', 'Check member Congress old decision such space.', 'Lucasmouth', 'Rejected', 'Travel think police billion recent student government.', 'Others gun forget send discuss.', 'Brother reality that similar forward should.', 2024-05-30, 2024-06-20, 'Kelly Hernandez', 'Allison Ray');
INSERT INTO VendorInformationRequest VALUES ('VIR-1955', 48, 'Doyle, Perez and Miller', '26992 Courtney Divide, Hannaview, OR 46963', 2901, 'Short Part', 'Medium', 'Road air health. Raise stop from.', 'Samanthabury', 'Approved', 'Detail meeting simply likely finally.', 'Long million college card discussion with between shake offer.', 'Direction raise then commercial nor fact worry century agreement understand Democrat throw.', 2025-03-08, 2025-03-25, 'Kristi Robinson', 'Erin Parker');
INSERT INTO VendorInformationRequest VALUES ('VIR-8767', 49, 'Rowland-Johnston', '971 Hall Unions Suite 561, Melendezmouth, VT 09847', 6745, 'True Part', 'Low', 'Move always safe community.', 'Jessicaton', 'Rejected', 'Skill represent morning meeting rise.', 'Operation image individual every until.', 'Nice market age power talk another bad partner feel also.', 2024-07-18, 2024-07-25, 'Samantha Rodriguez', 'Katrina Townsend');
INSERT INTO VendorInformationRequest VALUES ('VIR-9209', 50, 'Burke, Porter and Ruiz', '067 Jennifer Stream Suite 122, West Justinbury, NV 10574', 4660, 'Draw Part', 'Medium', 'Same still consumer example perhaps.', 'South Ryan', 'Under Review', 'Matter traditional yet game hundred car.', 'Discover some teach prove really away many nor.', 'Site treat whole religious expert side view old.', 2024-09-27, 2024-10-19, 'Leonard Myers', 'William Gordon');
INSERT INTO VendorInformationRequest VALUES ('VIR-5671', 51, 'Smith and Sons', '003 Gregory Knolls Suite 443, Brownborough, GA 76212', 5831, 'Do Part', 'High', 'Buy yard why couple.', 'West Julieview', 'Under Review', 'Member less recently possible after east.', 'Process sing half raise us call.', 'Year water Mrs without money magazine personal back improve evidence simple deal may.', 2024-11-23, 2024-11-30, 'Catherine Hernandez', 'Joseph Walker');
INSERT INTO VendorInformationRequest VALUES ('VIR-7585', 52, 'Hall, Wilson and Richard', '78544 Christopher Summit Suite 967, West Matthewmouth, ID 62150', 3616, 'Source Part', 'Low', 'Since thank think it.', 'New Joychester', 'Under Review', 'Single their prepare law behavior hold sense.', 'Send experience way decide institution if.', 'My movie major fact large action see expert American sport sister.', 2024-08-26, 2024-09-07, 'Julie Scott', 'Victoria Wilson');
INSERT INTO VendorInformationRequest VALUES ('VIR-6904', 53, 'Stephens-Powell', '07810 Proctor Lane Suite 111, North Joseph, KS 33862', 3908, 'Beyond Part', 'Low', 'Instead letter group keep country.', 'South Michael', 'Rejected', 'Sign run model bad.', 'His door save environment over wrong any system season later send.', 'Travel mind either leader keep activity any well glass edge room you.', 2024-08-11, 2024-09-02, 'David Morris', 'Jason Hernandez');
INSERT INTO VendorInformationRequest VALUES ('VIR-2598', 54, 'Lopez Inc', '2412 Julie Row, Lake Janebury, NE 87705', 8742, 'Management Part', 'Medium', 'Many across most few small front.', 'South Rebeccaburgh', 'Rejected', 'Build treatment live play.', 'No nearly office share dark once road.', 'More ahead up Democrat fish power nearly.', 2025-05-05, 2025-05-27, 'Jessica Robbins', 'Scott Mcclure');
INSERT INTO VendorInformationRequest VALUES ('VIR-7940', 55, 'Alvarado-Martinez', 'USCGC Morales, FPO AA 76756', 7759, 'Accept Part', 'Low', 'Popular draw final the.', 'Nelsonshire', 'Under Review', 'When real size give.', 'Who organization state beautiful day long matter five.', 'Me believe of report top single possible end Democrat any later despite.', 2025-03-20, 2025-04-12, 'Angela Sanford', 'Donald Gallegos');
INSERT INTO VendorInformationRequest VALUES ('VIR-5719', 56, 'Holloway-Harris', '869 Bowen Pine, East Glennfurt, CA 74362', 6837, 'Affect Part', 'Low', 'Thousand occur line while story.', 'Port Jenna', 'Approved', 'Once song event news.', 'Rock stand set central computer half network no.', 'Girl key show key other level husband doctor thus central decade tax level.', 2024-06-02, 2024-06-12, 'Kaitlin Pacheco', 'Yolanda Mora');
INSERT INTO VendorInformationRequest VALUES ('VIR-6252', 57, 'Simpson Inc', '84702 Nielsen Drive Suite 033, Bruceland, MT 62840', 4112, 'Subject Part', 'High', 'Feel message today sea sit.', 'Lake Lauraland', 'Approved', 'Put former fill realize visit.', 'Soldier economy analysis find think specific cost house understand already.', 'Interest result project almost skill table notice computer brother people music series energy.', 2024-08-14, 2024-09-09, 'Haley Welch', 'Brittany Dixon');
INSERT INTO VendorInformationRequest VALUES ('VIR-6580', 58, 'Grant-Ward', '3690 Navarro Turnpike, Mercadoland, NY 78595', 3754, 'Realize Part', 'Medium', 'Far black purpose whole old expect.', 'Larrystad', 'Approved', 'Skill between news goal scientist late.', 'Pay cover book since consumer morning responsibility.', 'Fact employee again floor need leg occur whatever image order.', 2025-05-02, 2025-05-08, 'Molly Stone', 'Kara Jackson');
INSERT INTO VendorInformationRequest VALUES ('VIR-1153', 59, 'Abbott, Warren and Mendoza', '0777 Steven Crest Suite 953, Robinsonland, MT 31642', 3235, 'Product Part', 'High', 'Religious particular message table leg not when.', 'Karenstad', 'Under Review', 'See recent box than standard rate fill.', 'Remember kind find if trial set.', 'Conference east what appear listen probably less debate order market own participant behind.', 2024-09-19, 2024-10-15, 'Stephen Hicks', 'William Stafford');
INSERT INTO VendorInformationRequest VALUES ('VIR-3044', 60, 'Todd, Ruiz and Williams', '0635 Washington Plains, Loganbury, UT 31006', 5723, 'Then Part', 'Low', 'Certain strong activity indicate cell require.', 'North Carolynville', 'Under Review', 'Wish them easy off officer factor art.', 'Care suffer officer listen security fact item face.', 'Simple whatever management staff already a ground face clear issue speak.', 2024-12-07, 2024-12-21, 'Brittney Ray', 'Laurie Williams');
INSERT INTO VendorInformationRequest VALUES ('VIR-4496', 61, 'Herman LLC', '7449 Ethan Corners, Johnsonport, LA 49931', 2832, 'Lose Part', 'High', 'Institution four area civil.', 'Johnsonfurt', 'Rejected', 'Network forward build treatment science partner seat.', 'Catch appear society finally control push follow.', 'Catch all pass soon case top assume character generation nor thousand change truth.', 2025-02-19, 2025-03-16, 'Benjamin Foster', 'Jonathon Morris');
INSERT INTO VendorInformationRequest VALUES ('VIR-3268', 62, 'Manning, Romero and Scott', '7089 Alvin Terrace Suite 403, East Elizabethchester, NJ 49623', 6899, 'Budget Part', 'Medium', 'Seven decide each throw state.', 'Williamstown', 'Rejected', 'Whom bar give sound go someone western Mrs.', 'Decade hold service benefit factor.', 'Lose not list girl leave pull another fire kid open involve.', 2025-02-28, 2025-03-12, 'Dustin Williams', 'Cameron Kennedy');
INSERT INTO VendorInformationRequest VALUES ('VIR-4330', 63, 'Lewis-Humphrey', '03369 Sharon Cove, West Roberta, WY 87756', 4104, 'Raise Part', 'Medium', 'Knowledge four mission them often film list.', 'Jaredburgh', 'Rejected', 'From dinner wonder table able generation during job.', 'Property treatment thought pay probably during.', 'Box pay party bank lawyer yet institution offer debate live front particular.', 2024-06-27, 2024-07-09, 'Thomas Hogan', 'Anthony Ross');
INSERT INTO VendorInformationRequest VALUES ('VIR-2902', 64, 'Bowman Ltd', '078 Reeves Cliffs, North George, SC 26685', 2558, 'Go Part', 'Low', 'Beyond tend exist always.', 'Port Anthony', 'Approved', 'Image teacher business body long job.', 'Truth voice mission tax popular throw.', 'Social former onto seem source others account of present right dog.', 2025-04-20, 2025-04-28, 'Vincent Alvarez', 'Sarah Ramirez');
INSERT INTO VendorInformationRequest VALUES ('VIR-6973', 65, 'Jefferson PLC', 'Unit 5741 Box 5806, DPO AA 65581', 5185, 'Opportunity Part', 'Low', 'Technology product control matter.', 'Hurleyview', 'Rejected', 'Environmental bad figure whole.', 'Try western wonder not conference share moment social.', 'Simply list job try individual should writer something.', 2024-12-24, 2024-12-26, 'Renee Bell', 'Gregory Wyatt');
INSERT INTO VendorInformationRequest VALUES ('VIR-9649', 66, 'Kline-Smith', '9871 Jackson Trafficway Apt. 321, West Jessicachester, NC 29890', 5445, 'World Part', 'High', 'While son ago more its group agree.', 'West Erinmouth', 'Under Review', 'Somebody forward organization west PM wrong specific.', 'Law skin challenge fall audience how south why born decision.', 'Reveal skill human use for effect feel prevent brother director.', 2024-07-31, 2024-08-26, 'Crystal Barajas', 'Angel Griffin');
INSERT INTO VendorInformationRequest VALUES ('VIR-7900', 67, 'Grimes and Sons', '44524 Donald Corners, North Michaelland, MN 36878', 3290, 'Where Part', 'Medium', 'Party candidate house decide.', 'Port Ryanberg', 'Rejected', 'Sit kid size catch.', 'Movement animal leave benefit top friend.', 'Rather first pattern bed too prevent watch leg dinner huge receive leader.', 2024-06-23, 2024-07-02, 'Willie Glass', 'Megan Brandt');
INSERT INTO VendorInformationRequest VALUES ('VIR-8064', 68, 'Thomas-Payne', '446 Martinez Greens, East Nicholasborough, WA 24419', 4659, 'Bank Part', 'Low', 'Worker walk leader.', 'Hermanport', 'Approved', 'Above sense task drug land prove affect computer.', 'Artist budget thing individual month audience foot include past catch.', 'Thought herself moment above beyond market yard human certainly.', 2024-11-26, 2024-12-06, 'Gary Phillips', 'Susan Ellis');
INSERT INTO VendorInformationRequest VALUES ('VIR-6070', 69, 'Black PLC', '40661 Spence Radial, Lake Kristinefort, UT 81558', 5685, 'Share Part', 'Medium', 'Many find someone within learn letter.', 'West Sonya', 'Rejected', 'Throw those cut land five.', 'Fear account north catch main reality teacher study.', 'Road quickly room per board outside sit tonight American compare choice.', 2025-03-28, 2025-04-01, 'Regina Fischer', 'Rebecca Castillo');
INSERT INTO VendorInformationRequest VALUES ('VIR-1064', 70, 'Miller PLC', '278 Michael Street, Sandersland, MO 09195', 1284, 'Along Part', 'Medium', 'Mr which discover of defense face.', 'Williamshire', 'Under Review', 'Surface meet different.', 'Statement customer three condition discover direction loss interesting detail everything.', 'Role watch item present tend least kid may meeting finish and expect.', 2024-05-23, 2024-06-08, 'Kathryn Lopez', 'Lisa Gilmore');
INSERT INTO VendorInformationRequest VALUES ('VIR-8351', 71, 'Kelly Ltd', '1142 Jones Forge Suite 029, Johnsonport, ND 88501', 9559, 'Heavy Part', 'High', 'Decision from event her stuff west wrong.', 'New Lisa', 'Under Review', 'Police resource officer brother just statement.', 'Issue note natural early old true thousand simply door ten.', 'Mother soon nor able federal summer letter week.', 2024-11-11, 2024-12-10, 'Crystal Wheeler', 'Donna Rivas');
INSERT INTO VendorInformationRequest VALUES ('VIR-9709', 72, 'Peters-Walter', '47553 Deanna Meadow, Housemouth, OR 52429', 4270, 'Water Part', 'High', 'Six reach director enough worker weight.', 'Mayland', 'Under Review', 'Ever seven father lead majority stand.', 'Stop watch set prove town will cultural.', 'North north economic chair someone eat direction reach back.', 2025-01-11, 2025-01-12, 'Noah Delgado', 'Brian West');
INSERT INTO VendorInformationRequest VALUES ('VIR-2236', 73, 'West, Case and Lopez', '042 Aaron Estates Suite 894, North Cynthia, OH 25694', 8378, 'Yeah Part', 'Low', 'Perhaps consumer commercial north.', 'New Raymondfort', 'Rejected', 'Show government run third.', 'Economic most since reflect whatever major someone follow describe night.', 'When off gas under large eye rock thousand affect upon food manager common.', 2025-03-13, 2025-03-17, 'Keith Glass', 'Alisha Velasquez');
INSERT INTO VendorInformationRequest VALUES ('VIR-4050', 74, 'Scott Group', '0484 Armstrong Glens Apt. 961, Torresport, CO 87161', 1505, 'Operation Part', 'High', 'Letter three suggest former.', 'Greenton', 'Rejected', 'Pm gas upon heart site type.', 'First day charge campaign challenge central view.', 'Break church heavy window peace whole.', 2024-10-24, 2024-11-03, 'Mr. John Oliver DVM', 'Connie Hansen');
INSERT INTO VendorInformationRequest VALUES ('VIR-4852', 75, 'Andersen-Keller', '646 Dean Cliff Apt. 046, Hillfurt, AL 07610', 5326, 'Then Part', 'Low', 'Wonder sure amount never. Focus key recent.', 'Sarafort', 'Under Review', 'Customer drive book hair continue.', 'Development paper rock begin these such defense be.', 'Of evening process memory friend head physical group hour talk lawyer.', 2025-01-10, 2025-01-27, 'Leonard Gonzalez', 'William King');
INSERT INTO VendorInformationRequest VALUES ('VIR-1770', 76, 'Morgan-Briggs', '1166 Jill Trail, Joseborough, WA 00706', 7702, 'Part Part', 'High', 'Skin business up benefit as like.', 'West William', 'Approved', 'Politics wall south short beat.', 'Themselves happy subject kind become political third.', 'Enough already cup travel director quite actually fact tax lead.', 2025-04-12, 2025-04-16, 'Anthony Jones', 'Amanda Brown');
INSERT INTO VendorInformationRequest VALUES ('VIR-3233', 77, 'Phillips-Carter', '7644 Jones Rest, South Cindyfort, ME 60978', 7840, 'Middle Part', 'Medium', 'Skin take discover cover free himself yes.', 'New Jonathan', 'Under Review', 'Second enter good occur write evening.', 'Ok rule available south stock ground moment change prepare find.', 'Actually too draw medical newspaper president five matter.', 2024-12-22, 2025-01-10, 'Megan Mora', 'Alejandro Smith');
INSERT INTO VendorInformationRequest VALUES ('VIR-8107', 78, 'Williams LLC', '76503 Jason Lane, East Zacharyton, ME 46086', 2925, 'Magazine Part', 'High', 'In option tonight particularly he.', 'East Christy', 'Under Review', 'Treatment other together official billion painting.', 'Project poor vote pressure trip.', 'Area mention seem foreign couple fund job mission they apply field dark maintain.', 2025-03-28, 2025-04-16, 'Andrew Chapman', 'Joseph Harding');
INSERT INTO VendorInformationRequest VALUES ('VIR-4644', 79, 'Bowman, Fisher and Price', '6999 Martin Creek Suite 148, Lake Johnburgh, VT 42878', 1937, 'Cell Part', 'Low', 'Director by different find him side.', 'West Zoeshire', 'Rejected', 'Leader ball material type modern rule.', 'Project fund right cup perform right life resource.', 'Good election several drop yeah new beautiful far important.', 2025-02-13, 2025-03-05, 'Jennifer Garcia', 'William Johnson');
INSERT INTO VendorInformationRequest VALUES ('VIR-2169', 80, 'Patterson-West', '9730 Schneider Keys, Lake Thomasmouth, WA 95868', 9462, 'Road Part', 'Medium', 'Player agreement hope.', 'North Matthew', 'Under Review', 'Manage course office push.', 'My recently argue yeah instead campaign bad loss nothing economic.', 'Himself that event account someone same production indeed although assume pressure book control.', 2024-11-03, 2024-11-15, 'Keith Garrison', 'Courtney Brooks');
INSERT INTO VendorInformationRequest VALUES ('VIR-8007', 81, 'Arroyo, Bennett and Walker', '76706 Nicholas Gardens, South Aaronborough, KS 79815', 9314, 'Situation Part', 'High', 'Trade why past.', 'South Nicoleport', 'Under Review', 'Most off foot short up teach.', 'Probably him paper success heart low push.', 'Carry quite officer war certainly home possible deep woman hotel effect.', 2024-12-16, 2025-01-14, 'Jose Forbes', 'Catherine Peterson');
INSERT INTO VendorInformationRequest VALUES ('VIR-7081', 82, 'Miller-Reese', '468 Suzanne Islands Apt. 185, Allenview, NY 15217', 8357, 'Then Part', 'High', 'Actually check smile to present coach foot.', 'Michellehaven', 'Approved', 'Table necessary win mouth laugh decide join.', 'Sound might office top hair all audience new language since.', 'People information set may chair business large response meeting about relationship project could with.', 2025-01-11, 2025-01-23, 'Mrs. Susan Adams', 'Karen Calhoun');
INSERT INTO VendorInformationRequest VALUES ('VIR-6777', 83, 'Acevedo, Rivera and Parker', '80404 James Island, Port Danielborough, CO 64049', 4136, 'Company Part', 'Medium', 'Character financial offer speech bank.', 'Port Gregory', 'Approved', 'Republican deal energy door ground across avoid.', 'Street number bag little international heart western laugh.', 'Green final skin simply theory third heart detail statement last only lead Mrs.', 2025-01-25, 2025-02-14, 'Brian Sexton', 'Joseph Washington');
INSERT INTO VendorInformationRequest VALUES ('VIR-9356', 84, 'Ramirez-Bentley', '4256 Jimenez Spurs, Leslieborough, TX 27944', 1179, 'Word Part', 'Medium', 'Soon else white bank she.', 'South David', 'Approved', 'Report seven country heart.', 'Democrat they cut physical side each yourself commercial mean sometimes.', 'During employee drop area education pay walk one must.', 2025-01-02, 2025-01-05, 'Valerie Kim', 'Jimmy Gordon');
INSERT INTO VendorInformationRequest VALUES ('VIR-2791', 85, 'Harris, Matthews and Elliott', '438 Jonathan Point Suite 188, Lake Lisa, UT 56168', 3912, 'Realize Part', 'Low', 'Culture people pay forward you.', 'Lake Emily', 'Rejected', 'From assume by bank sure religious well.', 'Cut check poor whole clearly maybe international kitchen.', 'Collection build audience why news per million realize environmental.', 2024-08-22, 2024-09-17, 'Cody Fischer', 'Brittany Harrison');
INSERT INTO VendorInformationRequest VALUES ('VIR-4797', 86, 'Ortiz, Hays and George', '84237 Christy Highway, South Connieport, WI 74471', 6807, 'Range Part', 'Low', 'Other remember white his thus ago media.', 'Port Tanyastad', 'Rejected', 'Relate method against test.', 'Top beautiful outside firm.', 'Bill for agency forward stock leg fast become support leave.', 2024-08-19, 2024-09-14, 'William Miller', 'Mr. Derrick Lane');
INSERT INTO VendorInformationRequest VALUES ('VIR-6477', 87, 'Ford-Hill', 'Unit 9235 Box 5128, DPO AE 82771', 1079, 'Letter Part', 'High', 'Growth effect involve according.', 'Stephanieside', 'Under Review', 'Away the skill morning season ability.', 'Maintain start author treat identify.', 'Act enough issue also energy range amount over.', 2024-09-03, 2024-09-23, 'Linda Cox', 'James Walsh');
INSERT INTO VendorInformationRequest VALUES ('VIR-2660', 88, 'Barnett and Sons', '55744 Martin Brooks, Clarkville, ND 58089', 1841, 'Month Part', 'High', 'Find information owner top risk purpose mention.', 'Williamsburgh', 'Under Review', 'Mind stand take whole training will.', 'From choice window play for matter here audience executive of.', 'Day side certainly describe significant yard record.', 2025-01-25, 2025-02-03, 'Joseph Rangel V', 'Jennifer Griffin');
INSERT INTO VendorInformationRequest VALUES ('VIR-2181', 89, 'Ferguson-Jacobs', '817 Julian Creek, Harrisstad, LA 21342', 5175, 'Thought Part', 'Medium', 'Leader action no management real wife somebody.', 'Lake Emilyshire', 'Under Review', 'Suffer occur anyone protect pay present.', 'Federal campaign both enough author air development compare.', 'However subject fight most tough notice future beat shoulder few fine prevent international program.', 2024-07-12, 2024-07-15, 'John Young', 'Brandon Jones');
INSERT INTO VendorInformationRequest VALUES ('VIR-6886', 90, 'Smith Ltd', '1150 Frank Orchard Apt. 713, Kyleland, NM 01897', 7946, 'Stock Part', 'High', 'Wish spring hospital exist century.', 'West Thomas', 'Under Review', 'Adult learn guess ball.', 'I early foreign form experience human.', 'Whole kind single stand church say send information defense yourself your everybody sea brother.', 2024-09-14, 2024-10-09, 'Samantha Mooney', 'Randy Joseph');
INSERT INTO VendorInformationRequest VALUES ('VIR-8215', 91, 'Bean-Miller', '65563 Marie Ports Suite 279, Port Nathan, NJ 09868', 8677, 'Easy Part', 'High', 'Evidence computer drug smile nearly service.', 'Marybury', 'Rejected', 'Blue western majority least live.', 'Friend view interest training watch quickly others describe animal some.', 'Yard quality follow fight few newspaper over citizen science whom year.', 2024-12-25, 2024-12-27, 'Elaine Gonzalez', 'Joseph Brown');
INSERT INTO VendorInformationRequest VALUES ('VIR-8991', 92, 'Allen PLC', '70367 Phillips Prairie Suite 729, New Gregory, AL 88209', 7866, 'Democratic Part', 'High', 'Here air foreign old somebody.', 'South Meganside', 'Approved', 'Rest go market.', 'Opportunity difficult head little future my from continue shoulder low.', 'Successful wall arm pretty manager radio main red.', 2024-09-17, 2024-09-23, 'Brian Ramsey', 'Kathryn Barnett');
INSERT INTO VendorInformationRequest VALUES ('VIR-3177', 93, 'Woods, Benton and Anderson', '40691 Jenna Heights, East Brianmouth, OK 10420', 7291, 'Machine Part', 'Low', 'Much compare campaign actually industry personal.', 'Grayland', 'Approved', 'Check who level after never accept personal.', 'Ground company citizen marriage consider plan.', 'Community somebody from according one magazine poor my ready.', 2024-10-06, 2024-11-04, 'Sarah Tucker', 'Tina Ferguson');
INSERT INTO VendorInformationRequest VALUES ('VIR-5733', 94, 'Turner Group', 'Unit 1244 Box 2743, DPO AA 95037', 1187, 'White Part', 'Medium', 'Win how little impact.', 'Albertborough', 'Under Review', 'Take area network court feel control.', 'Whether current spend truth either former.', 'Ever piece tough buy miss wish.', 2025-04-30, 2025-05-09, 'Anthony Wells', 'James Jackson');
INSERT INTO VendorInformationRequest VALUES ('VIR-5759', 95, 'Mitchell-Weber', '114 Travis Mews Apt. 142, Pollardhaven, WV 66910', 3879, 'Area Part', 'High', 'Ability necessary away election.', 'Lake Amy', 'Under Review', 'Position occur because appear.', 'Generation lead system no compare focus billion left.', 'Government choice customer field eye figure election four page deep nature film read.', 2024-09-19, 2024-10-08, 'Christopher Bradley', 'Michael Schroeder');
INSERT INTO VendorInformationRequest VALUES ('VIR-8290', 96, 'Palmer-Hopkins', '5761 Day Manors Suite 248, Port Michaelshire, MD 63544', 7130, 'Show Part', 'Medium', 'Stay than respond find choice court.', 'Millerton', 'Under Review', 'Vote clear visit half role imagine again.', 'Bar idea power what likely fall identify economic.', 'Heavy why stay soon strong discuss employee enough degree some.', 2024-09-30, 2024-10-03, 'Kimberly Williamson', 'Timothy Keller');
INSERT INTO VendorInformationRequest VALUES ('VIR-6031', 97, 'Mclaughlin, Giles and Perry', '446 Castaneda Alley Apt. 199, Port John, SC 53150', 3283, 'Professor Part', 'High', 'Represent his population oil.', 'Gardnerview', 'Rejected', 'Poor reduce nature sea issue.', 'Laugh project we ability information call.', 'Newspaper economic general fly should natural say federal system cut.', 2025-02-09, 2025-03-02, 'Ryan Nolan', 'Elizabeth Smith');
INSERT INTO VendorInformationRequest VALUES ('VIR-6482', 98, 'Bentley LLC', '7813 Angel Expressway Apt. 511, Ashleytown, KS 88249', 7044, 'Condition Part', 'High', 'Report step later method answer.', 'Fostermouth', 'Under Review', 'Card name unit idea answer.', 'Sport each past will music deep benefit we.', 'Single war really reveal adult event great positive.', 2025-03-19, 2025-04-18, 'Lisa Wang', 'Jean Mccarthy');
INSERT INTO VendorInformationRequest VALUES ('VIR-9414', 99, 'Lewis, Hernandez and Williams', '350 Matthew Springs Apt. 802, North Josephchester, KS 17917', 1072, 'Indicate Part', 'Low', 'Can happen key development than describe.', 'Jeffreyborough', 'Approved', 'Short indeed building blood white way.', 'Lay weight person early town president usually grow mission involve.', 'Specific above team other Republican whether attack from parent marriage teacher in every.', 2025-02-27, 2025-03-26, 'Stephanie Ferguson', 'Mary Martinez');
INSERT INTO VendorInformationRequest VALUES ('VIR-7612', 100, 'Jones Ltd', '68316 Ruben Fall, New Adam, OK 17975', 6445, 'Ground Part', 'Medium', 'Cut represent capital whose material worry.', 'South April', 'Approved', 'Scientist sign important ok wait check.', 'Country up account ability fine.', 'Way within like create rest article general also hand increase spring gas develop.', 2024-05-25, 2024-06-22, 'Heather Moss', 'Richard Brown');
